---
title: '201810.3'
output: html_document
---
```{r}
library(stringr)
library(readr)
studentID <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/studentID.csv")
str_sub(studentID, start = 7, end = 11)

```
```{r}
hw <- "Hadley Wickham"

str_sub(hw, 1, 6)
str_sub(hw, end = 6)
str_sub(hw, 8, 14)
str_sub(hw, 8)
str_sub(hw, c(1, 8), c(6, 14))

```

```{r}
str_c(letters,LETTERS)
str_c(letters,LETTERS,sep="-")
str_c("lowercase: ", letters, ", capital: ", LETTERS)
```
```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
```
```{r}
githubData[c(2,3,4),] -> sampleGithub
str_c(sampleGithub$`GitHub username`,
      sampleGithub$`GitHub repo name`)
str_c("https://github.com/",
      sampleGithub$`GitHub username`,
      "/",
      sampleGithub$`GitHub repo name`)
```
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
str_split(filmvotingdata,","2)
```
```{r}
民國年月<-c("099/01","099/02","099/03")
str_c("1",c,"/01")
```

```{r}
12+3*6
2^5
1.55e5
foo=23
foo
sum(1:100)
class(2+3i)
c("hello","world")
class(c)
gender=factor(c("male","female","male"))
gender
levels(gender)
gender.char=sample(c("male","female"),500,replace=T)
jr=as.factor(gender.char)
gender.factor
object.size(gender.char)
object.size(gender.factor)
x="1.52"
as.numeric(x)
sss=c(1,4,16,5)
for(x in sss){print(x+5)}
print(x)
x=rnorm(15)
x
summary(x)
y=sample(c("a","b","c"),10,replace=T)
y
summary(y)
y.factor=factor(y)
summary(y.factor)
str(y)
yx.df=data.frame(y,x)
head(yx.df)
unclass(y.factor)
```
```{r}
x=1:10
y=1:20
x
data.frame(x,y)
xy=data.frame(x,y)
head(xy)
summary(xy)
str(xy)
ls()
n=20
seq=1:n-1
seq
seq1=1:(n-1)
seq(1:10)
rep(x,times=2)
aaa=x<5
aaa
str=c("a1","a2")
str
str(c)
x=10
str=paste("x=",x)
str
z=x[x>5]
z
fruit=c(5,10,1,20)
names(fruit)=c("orange","banana","apple","peach")
fruit
data.frame(fruit)
lunch=fruit["apple"]
lunch

```

```{r}
vector("numeric",4)
c(d=2,f=3)
x=c
nchar(x)
length(c(d=2,f=3))
levels(student$出生地)
class(student$出生地)
as.character(student$出生地)
x <- gl(2, 4, 8)
levels(x)[1] <- "low"
a<-"2017-01-31"
class(a)
library(dplyr)
library(lubridate)
a <- ymd("2017-01-31") 
b <- ymd_hms("2017-01-31 20:11:59")
a
str_c(letters,LETTERS)
str_c(letters,LETTERS,sep="-")
str_c("lowercase: ", letters, ", capital: ", LETTERS)
c(2L, 'a', 3.0, 4)
x=c
class(2L)
class(c(2L, 'a', 3.0, 4))
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
head(student,10)
gender <- c("男性", "男性", "女性", "男性", "女性", "男性")
levels=c("男性", "男性", "女性", "男性", "女性", "男性")
labels = c("Male", "Female")
gender
gender
gender <- factor(x = gender, levels = c("男性", "女性"), labels = c("Male", "Female"))
x
colors <- c("red", "yellow", "green", "red", "green")
colors.factor <- factor(colors)
colors.factor
```


